Preparation/Technical task/CargoTransportation (part 2)/CargoTransportation/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :requests
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  root 'admin/requests#index'
end

Preparation/Technical task/CargoTransportation (part 2)/CargoTransportation/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Preparation/Technical task/CargoTransportation (part 2)/CargoTransportation/app/models/request.rb
# frozen_string_literal: true

class Request < ApplicationRecord
  validates :weight, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :length, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :width, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :height, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :name, presence: true
  validates :surname, presence: true
  validates :patronymic, presence: true
  validates :phone_number, presence: true, length: { is: 11 }, numericality: { only_integer: true }
  validates :point_of_departure, presence: true
  validates :destination, presence: true
  validates :email, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at destination distance email height id id_value length name patronymic
       phone_number point_of_departure price surname updated_at weight width]
  end
end

Preparation/Technical task/CargoTransportation (part 2)/CargoTransportation/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

Preparation/Technical task/CargoTransportation (part 2)/CargoTransportation/app/controllers/requests_controller.rb
# frozen_string_literal: true

class RequestsController < InheritedResources::Base
end

Preparation/Technical task/CargoTransportation (part 2)/CargoTransportation/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

Preparation/Technical task/CargoTransportation (part 2)/CargoTransportation/app/helpers/requests_helper.rb
# frozen_string_literal: true

module RequestsHelper
end

Preparation/Technical task/CargoTransportation (part 2)/CargoTransportation/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CargoTransportation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Preparation/Technical task/CargoTransportation (part 2)/CargoTransportation/app/views/requests/_form.html.erb
<%= form_with(model: request) do |form| %>
  <% if request.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.text_field :weight %>
  </div>

  <div>
    <%= form.label :length, style: "display: block" %>
    <%= form.text_field :length %>
  </div>

  <div>
    <%= form.label :width, style: "display: block" %>
    <%= form.text_field :width %>
  </div>

  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.text_field :height %>
  </div>

  <div>
    <%= form.label :distance, style: "display: block" %>
    <%= form.text_field :distance %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :point_of_departure, style: "display: block" %>
    <%= form.text_field :point_of_departure %>
  </div>

  <div>
    <%= form.label :destination, style: "display: block" %>
    <%= form.text_field :destination %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :surname, style: "display: block" %>
    <%= form.text_field :surname %>
  </div>

  <div>
    <%= form.label :patronymic, style: "display: block" %>
    <%= form.text_field :patronymic %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Preparation/Technical task/CargoTransportation (part 2)/CargoTransportation/app/views/requests/_request.html.erb
<div id="<%= dom_id request %>">
  <p>
    <strong>Weight:</strong>
    <%= request.weight %>
  </p>

  <p>
    <strong>Length:</strong>
    <%= request.length %>
  </p>

  <p>
    <strong>Width:</strong>
    <%= request.width %>
  </p>

  <p>
    <strong>Height:</strong>
    <%= request.height %>
  </p>

  <p>
    <strong>Distance:</strong>
    <%= request.distance %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= request.price %>
  </p>

  <p>
    <strong>Point of departure:</strong>
    <%= request.point_of_departure %>
  </p>

  <p>
    <strong>Destination:</strong>
    <%= request.destination %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= request.name %>
  </p>

  <p>
    <strong>Surname:</strong>
    <%= request.surname %>
  </p>

  <p>
    <strong>Patronymic:</strong>
    <%= request.patronymic %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= request.phone_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= request.email %>
  </p>

</div>

Preparation/Technical task/CargoTransportation (part 2)/CargoTransportation/app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render "form", request: @request %>

<br>

<div>
  <%= link_to "Show this request", @request %> |
  <%= link_to "Back to requests", requests_path %>
</div>

Preparation/Technical task/CargoTransportation (part 2)/CargoTransportation/app/views/requests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Requests</h1>

<div id="requests">
  <% @requests.each do |request| %>
    <%= render request %>
    <p>
      <%= link_to "Show this request", request %>
    </p>
  <% end %>
</div>

<%= link_to "New request", new_request_path %>

Preparation/Technical task/CargoTransportation (part 2)/CargoTransportation/app/views/requests/new.html.erb
<h1>New request</h1>

<%= render "form", request: @request %>

<br>

<div>
  <%= link_to "Back to requests", requests_path %>
</div>

Preparation/Technical task/CargoTransportation (part 2)/CargoTransportation/app/views/requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @request %>

<div>
  <%= link_to "Edit this request", edit_request_path(@request) %> |
  <%= link_to "Back to requests", requests_path %>

  <%= button_to "Destroy this request", @request, method: :delete %>
</div>